variable "vnet_name" {}
variable "location" {}
variable "resource_group_name" {}
variable "cidrblock" {}
variable "dns_servers" {}
variable "privatesubnetname" {}
variable "privatesubnetcidr" {}
variable "publicsubnetname" {}
variable "publicsubnetcidr" {}
variable "teamtag" {}
variable "typetag" {}