resources
| where type == 'microsoft.compute/virtualmachines'
| extend resourceId = tolower(id)
| join kind = leftouter (resources
| where type == 'microsoft.compute/virtualmachines/extensions' and name has 'MDE'
| extend resourceId = tolower((split(id, "/extensions"))[0]), state = properties.provisioningState
) on resourceId
| project name, location, resourceGroup, name1, ['state']
| where name1 == 'MDE.Linux' or name1 == 'MDE.Windows'