variable "resource_group_name" {}
variable "location" {}
variable "pub_ip_allo_method" {}
variable "pub_ip_sku" {}
variable "pub_ip_name" {}
variable "fwname" {}
variable "vnet_name" {}
variable "sku_tier" {}
variable "sku_name" {}
variable "ip_config_name" {}
variable "cidrblock" {}
variable "privatesubnetname" {}
variable "privatesubnetcidr" {}
variable "publicsubnetname" {}
variable "publicsubnetcidr" {}
variable "firewallsubnetname" {}
variable "firewallsubnetcidr" {}
variable "teamtag" {}
variable "typevnettag" {}
variable "typefwtag" {}
